### ISSUE TITLE
Spectating Function

### ISSUE THREAD

**Issue by Adohgg** [rmct/AutoReferee#126]
Usage: `/spectate authorblues`

Display authorblues complete vision, including inventory, to the user who executes that command. Sort of like [this](http://dev.bukkit.org/server-mods/spectate/), but less clunky.

**Comment by net** [comment]
AutoRef now uses 1.8 spectating which is similar to this. (minus the inventory viewing). Hopefully Mojang will update the gamemode to include this. Closed for now.
