### ISSUE TITLE
Non-ops don't have access to the '/ar unload' command

### ISSUE THREAD

**Issue by skitrip42** [rmct/AutoReferee#250]
An issue with the play server is that people often load a large number of maps and have no way to unload them, causing crashes. A way to avoid this would be giving all players access to the '/ar unload' command, but only in situations where all the players are on the same team, or the match has finished, so that a player can't unload the map during a match.

An alternative way to resolve the issue could to automatically unload maps if there aren't any players on a map for a certain amount of time.

**Comment by parkervcp** [comment]
I know it's supposed to unload after a certain amount of time after a match is completed.

I thought it unloaded maps that were empty for something like 15 minutes

**Comment by skitrip42** [comment]
From this page: http://rmct.github.io/AutoReferee/server.html, it looks like you can indeed configure a server to unload a map a certain number of seconds after the match ends.

I think you're also right about empty maps after a certain amount of time, because I just tried loading a map and then logging out, and then when I logged back in around 15 minutes later, I was in the lobby.

From what I gather, the play server does still crash from too many maps being loaded (for example most recently, Ben was speedrunning and so ended up loading a lot of maps). Perhaps a solution could be to make time taken for an empty map to unload into a setting that can be configured for individual servers, and then reduce it for the play server.
